[project]
name = "mak"
version = "0.0.0"
description = "Create Chains or Singular commands with an alias. Basically Makros, in the Terminal."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "orjson>=3.10.18",
    "typer>=0.16.0",
]
